import { frameSize, AudioMeter } from '/static/js/live.js';
import { state, renderAnswer } from '/static/js/chat.js';
const report = document.createElement('pre'); report.id = 'browser-check-results'; report.style = 'position:fixed;inset:8px 8px auto auto;max-width:430px;z-index:10000;background:white;border:1px solid #ccc;padding:12px;font-size:11px;white-space:pre-wrap'; document.body.append(report);
let passes = 0;
const pause = (ms) => new Promise(r => setTimeout(r, ms));
function ok(condition, label) { if (!condition) throw Error(label); passes++; report.textContent += `PASS ${label}\n`; }
async function until(fn) { for (let i = 0; i < 260; i++) { if (fn()) return; await pause(30); } throw Error('Timed out waiting for browser state'); }
function submit(text) { document.querySelector('#message').value = text; document.querySelector('#chat-form').requestSubmit(); }
try {
  submit('I prefer spicy chicken biryani and usually stay under ₹300.');
  submit('duplicate');
  await until(() => checks.watches.length);
  ok(checks.posts.length === 1, 'duplicate Send creates one run');
  const placeholder = document.querySelector('.message.assistant');
  await until(() => !state.busy);
  ok(document.querySelector('.message.assistant') === placeholder, 'stages and final reuse one assistant element');
  ok(placeholder.textContent.includes('Your preferences can carry forward.'), 'final answer renders');
  ok(checks.watches[0].closed, 'done closes EventSource');
  ok(state.conversationId === 'cid-1', 'returned conversation ID is stored');
  document.querySelector('#new-chat').click();
  ok(state.conversationId === null && !state.messages.length, 'New Chat clears conversation and visible messages');
  ok(localStorage.getItem('curio_user_id') === 'demo-sai' && checks.memories.length === 2, 'New Chat preserves identity and server memories');
  checks.failStream = true; submit("I'm hungry."); await until(() => !state.busy);
  ok(checks.posts.length === 2 && state.conversationId === 'cid-2', 'failed SSE recovers status without another POST');
  ok(checks.posts[1].user_id === 'demo-sai' && !checks.posts[1].conversation_id, 'new conversation uses same user');
  document.querySelector('#memories-button').click();
  await until(() => document.querySelectorAll('.memory-card').length === 2);
  ok(document.querySelector('#memory-cards').textContent.includes('spicy chicken biryani'), 'memory cards show backend values');
  ok(!document.querySelector('#memory-cards').textContent.includes('m1'), 'memory cards hide database IDs');
  document.querySelector('#memory-dialog').close();
  checks.unavailable = true; submit('Offline test'); await until(() => !state.busy);
  ok(document.querySelector('.message.assistant:last-child').textContent.includes('offline'), 'backend unavailable is explained');
  checks.unavailable = false;
  document.querySelector('#open-live').click();
  await until(() => !document.querySelector('#live-send').disabled);
  ok(checks.liveSent[0].type === 'configure' && checks.sockets[0].url.endsWith('/live/ws/demo-sai'), 'Live waits for ready and configures the same user');
  document.querySelector('#enable-camera').click(); await until(() => document.querySelector('#live-observation').textContent.includes('declined'));
  ok(document.querySelector('#live-observation').textContent.includes('still ask'), 'camera denial keeps text Live usable');
  checks.cameraDenied = false; document.querySelector('#enable-camera').click();
  await until(() => checks.liveSent.some(e => e.type === 'frame'));
  const frame = checks.liveSent.find(e => e.type === 'frame');
  ok(!frame.jpeg.startsWith('data:') && atob(frame.jpeg).length <= 512 * 1024, 'sampled camera sends bounded raw JPEG base64');
  const bitmap = await createImageBitmap(new Blob([Uint8Array.from(atob(frame.jpeg), c => c.charCodeAt(0))], { type: 'image/jpeg' }));
  ok(Math.max(bitmap.width, bitmap.height) <= 1280 && bitmap.width / bitmap.height > 1.7, 'JPEG dimensions preserve aspect and stay within 1280'); bitmap.close();
  ok(document.querySelector('#camera').videoWidth > 0 && document.querySelector('#camera-empty').hidden, 'local camera preview plays');
  await until(() => !document.querySelector('#live-send').disabled);
  const framesBefore = checks.liveSent.filter(e => e.type === 'frame').length;
  await pause(120); ok(checks.liveSent.filter(e => e.type === 'frame').length === framesBefore, 'camera does not stream preview FPS');
  document.querySelector('#live-mode').value = 'shopping'; document.querySelector('#live-mode').dispatchEvent(new Event('change'));
  await until(() => !document.querySelector('#live-send').disabled);
  ok(checks.liveSent.filter(e => e.type === 'configure').at(-1).mode === 'shopping', 'Shopping sends the existing backend mode');
  checks.microphoneDenied = true; document.querySelector('#live-microphone').click();
  await until(() => document.querySelector('#live-state').textContent.includes('Microphone access was declined'));
  ok(true, 'microphone denial is explained'); checks.microphoneDenied = false;
  const beforeVoice = checks.liveSent.length; document.querySelector('#live-microphone').click();
  await until(() => document.querySelector('#live-message').value.includes('dictated'));
  ok(checks.liveSent.length === beforeVoice, 'dictation fills composer without starting inference');
  document.querySelector('#live-form').requestSubmit();
  ok(document.querySelector('#live-send').disabled, 'Live guards duplicate question while reasoning');
  await pause(100); ok(checks.liveSent.filter(e => e.type === 'frame').length === framesBefore, 'no camera frame is sent during reasoning');
  await until(() => !document.querySelector('#live-send').disabled);
  ok(document.querySelector('#live-answer').textContent === 'A useful next step.', 'Live final answer renders');
  document.querySelector('#live-mode').value = 'interview'; document.querySelector('#live-mode').dispatchEvent(new Event('change'));
  await until(() => !document.querySelector('#live-send').disabled);
  ok(checks.liveSent.filter(e => e.type === 'configure').at(-1).mode === 'interview' && !document.querySelector('#audio-metrics-toggle').hidden, 'Mock Interview enables communication sampling');
  const meter = new AudioMeter(); await meter.start(); meter.last = performance.now() - 100; meter.sample(); checks.silent = true;
  for (let i = 0; i < 5; i++) { meter.last = performance.now() - 100; meter.sample(); } await meter.stop();
  const metrics = meter.metrics(); ok(metrics.duration_seconds > 0 && metrics.speaking_seconds > 0 && metrics.pause_count === 1 && metrics.rms.length <= 600, 'audio metrics contain bounded RMS and observable timing');
  ok(!('audio' in metrics) && Object.keys(metrics).length === 4, 'no raw audio or psychological fields');
  checks.sockets.at(-1).receive({ type: 'frame_skipped', reason: 'inference_in_progress' });
  const beforeSkip = checks.liveSent.length; await pause(150);
  ok(checks.liveSent.length === beforeSkip && document.querySelector('#live-state').textContent.includes('Pausing'), 'frame_skipped triggers backoff without a stale queue');
  await until(() => !document.querySelector('#live-mode').disabled);
  document.querySelector('#live-mode').value = 'discovery'; document.querySelector('#live-mode').dispatchEvent(new Event('change'));
  await until(() => !document.querySelector('#live-send').disabled);
  ok(checks.liveSent.filter(e => e.type === 'configure').at(-1).mode === 'discovery', 'Service Discovery sends the existing backend mode');
  const cameraTracks = document.querySelector('#camera').srcObject.getTracks(); document.querySelector('#close-live').click();
  await until(() => !document.querySelector('#live-dialog').open);
  ok(checks.sockets.at(-1).readyState === 3, 'closing Live closes its socket');
  ok(cameraTracks.every(track => track.readyState === 'ended'), 'closing Live stops camera tracks');
  ok(frameSize(1920, 1080).width === 1280 && frameSize(600, 1200).height === 1200, 'frame sizing handles landscape and portrait');
  document.querySelector('#discovery-button').click(); await until(() => document.querySelector('#budget').value === '300');
  ok(document.querySelector('#preferences').value === 'spicy chicken biryani', 'discovery form reads actual saved preferences');
  document.querySelector('#discovery-form').requestSubmit(); await until(() => document.querySelectorAll('.recommendation').length === 1);
  ok(document.querySelector('#discovery-results').textContent.includes('Fictional demo') && document.querySelector('#discovery-results').textContent.includes('Within your budget'), 'recommendation cards display backend reasons and fictional label');
  document.querySelector('#discovery-dialog').close();
  document.querySelector('#open-live').click(); await until(() => !document.querySelector('#live-send').disabled);
  document.querySelector('#live-message').value = 'Finish this answer after I close the camera'; document.querySelector('#live-form').requestSubmit();
  await until(() => state.busy); document.querySelector('#close-live').click();
  ok(!document.querySelector('#live-dialog').open, 'Live can close promptly while a submitted answer continues');
  await until(() => !state.busy); ok(checks.sockets.at(-1).readyState === 3, 'background Live reply completes then releases the socket');
  const safe = document.createElement('div'); renderAnswer(safe, '**Bold**\n- One\n<script>window.bad=1</script>\n[Bad](javascript:alert(1))');
  ok(safe.querySelector('strong')?.textContent === 'Bold' && safe.querySelector('li')?.textContent === 'One', 'answer formatting renders emphasis and lists');
  ok(!safe.querySelector('script') && !safe.querySelector('a'), 'answer formatting treats HTML and unsafe links as text');
  renderAnswer(safe, 'See [restaurant](https://www.zomato.com/hyderabad/example) and https://example.com/menu.');
  ok(safe.querySelector('.source-link.zomato')?.textContent.includes('Open on Zomato'), 'real source URLs render a Zomato action');
  ok([...safe.querySelectorAll('a')].every(a => a.target === '_blank' && a.rel.includes('noopener')), 'source links open only on a user click with safe attributes');
  renderAnswer(safe, '| Option | Price |\n|---|---|\n| **Demo** | ₹280 |');
  ok(safe.querySelector('th')?.textContent==='Option' && safe.querySelector('td strong')?.textContent==='Demo', 'recommendation tables render safe readable columns');
  document.querySelector('#show-inspector').checked = false; document.querySelector('#show-inspector').dispatchEvent(new Event('change'));
  ok(document.body.classList.contains('hide-inspector'), 'confirmed activity inspector can be hidden');
  report.textContent += `\n${passes} browser checks passed`;
} catch (error) { report.textContent += `\nFAIL ${error.stack}`; }
